#!/bin/bash
#Launch my website

export FLASK_APP=slippc-viz
export FLASK_DEBUG=1
#Run locally
tmux new-session -ds slippc-viz "FLASK_APP=slippc-viz FLASK_DEBUG=1 flask run"
#Run in production
# tmux new-session -ds pretzel-bar "FLASK_APP=pretzel-bar FLASK_DEBUG=1 flask run --host=0.0.0.0"
tmux switch-client -t slippc-viz
