"""added filedir to replays

Revision ID: 2cec4e0019bc
Revises: a9bccb24ae5d
Create Date: 2020-05-18 20:55:27.642986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cec4e0019bc'
down_revision = 'a9bccb24ae5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replay', sa.Column('filedir', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('replay', 'filedir')
    # ### end Alembic commands ###
