"""empty message

Revision ID: 80ff3ad84b07
Revises: d43fd0f3a327
Create Date: 2019-11-13 02:24:20.977790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ff3ad84b07'
down_revision = 'd43fd0f3a327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replay', sa.Column('p1display', sa.String(length=128), nullable=True))
    op.add_column('replay', sa.Column('p2display', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('replay', 'p2display')
    op.drop_column('replay', 'p1display')
    # ### end Alembic commands ###
