"""empty message

Revision ID: d43fd0f3a327
Revises: cd19d59a80f8
Create Date: 2019-11-13 01:43:36.671110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd43fd0f3a327'
down_revision = 'cd19d59a80f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replay', sa.Column('p1char', sa.Integer(), nullable=True))
    op.add_column('replay', sa.Column('p1color', sa.Integer(), nullable=True))
    op.add_column('replay', sa.Column('p1csstag', sa.String(length=8), nullable=True))
    op.add_column('replay', sa.Column('p1metatag', sa.String(length=128), nullable=True))
    op.add_column('replay', sa.Column('p1stocks', sa.Integer(), nullable=True))
    op.add_column('replay', sa.Column('p2char', sa.Integer(), nullable=True))
    op.add_column('replay', sa.Column('p2color', sa.Integer(), nullable=True))
    op.add_column('replay', sa.Column('p2csstag', sa.String(length=8), nullable=True))
    op.add_column('replay', sa.Column('p2metatag', sa.String(length=128), nullable=True))
    op.add_column('replay', sa.Column('p2stocks', sa.Integer(), nullable=True))
    op.add_column('replay', sa.Column('played', sa.DateTime(), nullable=True))
    op.add_column('replay', sa.Column('stage', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_replay_played'), 'replay', ['played'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_replay_played'), table_name='replay')
    op.drop_column('replay', 'stage')
    op.drop_column('replay', 'played')
    op.drop_column('replay', 'p2stocks')
    op.drop_column('replay', 'p2metatag')
    op.drop_column('replay', 'p2csstag')
    op.drop_column('replay', 'p2color')
    op.drop_column('replay', 'p2char')
    op.drop_column('replay', 'p1stocks')
    op.drop_column('replay', 'p1metatag')
    op.drop_column('replay', 'p1csstag')
    op.drop_column('replay', 'p1color')
    op.drop_column('replay', 'p1char')
    # ### end Alembic commands ###
